name: Deploy to EC2 (Apache)

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy index.html to Apache web root
        run: |
          sudo cp -f index.html /var/www/html/index.html
          sudo chown root:root /var/www/html/index.html
          sudo chmod 644 /var/www/html/index.html
          sudo systemctl restart httpd

      - name: Show Apache status
        run: |
          sudo systemctl status httpd --no-pager
          curl -I http://localhost
